#!/usr/bin/perl

#
# -------------------------------------------------
#
# - File..........: catepod
# - Author........: daemonize <marckloppenburg@gmx.de>
# - Discription...: Simple daemon construct that does the usual daemon,
#                   housekeeping, daemonizing, logging, privilege dropping,
#                   pid file management, interact different gameserver types,
#                   manage user, etc...
# - License.......: GPLv2
# - Created.......: 01 Jun 2009 by <daemonize@catepo.net>
#
# -------------------------------------------------
#

use strict;
use warnings;

use POE;
use POE::Wheel::FollowTail;
use Proc::Daemon;

use Catepod::Logger;
use Catepod::GsLogger;

use Privileges::Drop;
use JSON;
use Fcntl qw/:flock/;

use DBI;

use File::Path;
use Linux::usermod;

my $configfile = shift @ARGV;
my $conf;

{
    open my $fh, '<', $configfile or die "Couldn't open config file: $!";
    local $/;
    my $content = <$fh>;
    $conf = from_json($content);
    close $fh;
}

my $RUNAS_USER     = $conf->{runas_user};
my $DAEMONIZE      = $conf->{daemonize};
my $NAME           = $conf->{logname};
my $PIDFILE        = $conf->{pidfile};
my $PIPE_DIRECTORY = $conf->{pipe_dir};
my $GSWI_DIR       = $conf->{gswi_dir};
my $GAMES          = $conf->{games};
my $PACKAGE_DIR    = $conf->{packagedir};

my $VERSION = 0.1;

#
# Workflow:
# - Check if we run as root
# - check PID file
# - Daemonize
# - open log
# - open pipe
# - look up user id to drop privileges to
# - drop privileges
# - process commands
#

die "Must run as root" unless $> == 0;

# Daemonizing
Proc::Daemon::Init() if $DAEMONIZE;

# Open log
our $logger   = Catepod::Logger->new($NAME);
our $gslogger = Catepod::GsLogger->new($NAME);

sub DEBUG() {

    #eval {
    #    my $debuggmsg = ( caller 2 )[3];
    #    $logger->info("DEBUG: $debuggmsg");
    #};
}

open my $lockfile, '>', $PIDFILE
  or $logger->error("Couldn't open $PIDFILE for writing: $!");
flock( $lockfile, LOCK_EX | LOCK_NB )
  or $logger->error("Couldn't lock $PIDFILE, perhaps another instance of $NAME is running already?");

print {$lockfile} $$ . "\n"
  or $logger->error("Couldn't write PID ($$) to $PIDFILE: $!");

#drop_privileges($RUNAS_USER);

POE::Session->create(
    inline_states => {
        _start   => \&start,
        _stop    => \&stop,
        _default => sub {
            my ( $event, $args ) = @_[ ARG0, ARG1 ];

            #$logger->warn("Received unknown signal: $event");
        },
        sig_shutdown      => \&sig_shutdown,
        pipe_data         => \&pipe_data,
        pipe_reset        => \&pipe_reset,
        process_command   => \&process_command,
        pipe_error        => \&pipe_error,
        add_gameserver    => \&add_gameserver,
        delete_gameserver => \&delete_gameserver,
        nightlyrestart    => \&nightlyrestart,
    },
    heap => { gameserver => {}, }
);

POE::Kernel->run();

sub nightlyrestart {
    DEBUG;
    $logger->warn("Starting nightly restart of gameservers");

    my $dsn = "DBI:mysql:database=gswi;host=localhost;port=3306";
    my $dbh = DBI->connect( $dsn, 'root', 'k23771' );

    my $sth = $dbh->prepare(qq{SELECT * FROM gswi_nightlyrestart});
    $sth->execute();

    while ( my $ref = $sth->fetchrow_hashref ) {
        my $gsID = $ref->{gsID};

        $gslogger->warn( "Nightlyrestart restart", $gsID );
        $gslogger->setstatus( "nightlyrestart", $gsID );

        my $sth1 = $dbh->prepare(qq{SELECT * FROM gswi_gameserver WHERE gsID="$gsID"});
        $sth1->execute();

        my $ref1  = $sth1->fetchrow_hashref();
        my $owner = $ref1->{owner};

        my $sth2 = $dbh->prepare(qq{SELECT * FROM gswi_user WHERE userID="$owner"});
        $sth2->execute();
        my $ref2 = $sth2->fetchrow_hashref();
        my $user = $ref2->{user};

        my $port   = $ref1->{port};
        my $game   = $ref1->{game};
        my $ip     = $ref1->{ip};
        my $tick   = $ref1->{tickrate};
        my $map    = $ref1->{'map'};
        my $player = $ref1->{player};
        my $update = $ref1->{autoupdate};
        my $pboost = $ref1->{pingboost};

        my $path = $GSWI_DIR . "gameserver/$user/$port/";

        if ( !chdir($path) ) {
            $logger->warn("Couldn't chdir to $path to restart it.");
            $gslogger->warn( "Couldn't chdir to $path to restart it.", $gsID );
            $gslogger->setstatus( "nightlyrestartfail", $gsID );
            return;
        }

        my $excutable;
        my $poco_start;
        my $start_game;

        if ( $game eq 'cs' ) {
            $poco_start = 'counter-strike';
            $excutable  = 'hlds_run';
            $pboost     = '""';
            $start_game = 'cstrike';
        }
        elsif ( $game eq 'css' ) {
            $poco_start = 'counter-strike-source';
            $excutable  = 'srcds_run';
            $pboost     = ', "-pingboost", "' . $pboost . '"';
            $start_game = 'cstrike';
        }
        elsif ( $game eq 'dod' ) {
            $excutable  = 'hlds_run';
            $poco_start = 'day-of-defeat';
            $pboost     = '""';
            $start_game = 'dod';
        }
        elsif ( $game eq 'dods' ) {
            $excutable  = 'srcds_run';
            $poco_start = 'day-of-defeat-source';
            $pboost     = ', "-pingboost", "' . $pboost . '"';
            $start_game = 'dod';
        }

        if ($update) {
            $update = ', "-autoupdate"';
        }
        else { $update = ''; }

        unless ( $port >= 1024 && $port <= 65535 ) {
            $logger->warn("server port: '$port' is to low, or to high.");
            return;
        }

        unless ( $poco_start = $conf->{games}->{$poco_start} ) {
            $logger->warn(
                "Do not know what to do with game '$game', perhaps you forgot to specify a poco for it in the config?"
            );
            return;
        }

        my $params =
'{"params":["-game", "$start_game", "+map", "$map", "+maxplayers", "$player", "-port", "$port", "-tickrate", "$tick"]}';

        my $hashref;
        eval { $hashref = from_json($params); };

        my @params = $hashref->{params};

        #$pboost,       $update

        my @prm = "@params";

        print "@prm";

        my $foo         = @params;
        my $param_count = @params;

        unless ( $param_count > 0 ) {
            $logger->warn("cannot start gameserver '$port' without params.");
            return;
        }

        unless ($gsID) {
            $logger->warn("You don't gave me the server ID, exiting...");
            return;
        }

        $logger->info($param_count);

        #$logger->info( "Starting $poco_start with params: '" . "@$param_count" . "' in: '$path'" );

        my $require_name = $poco_start;
        $require_name =~ s/::/\//g;
        $require_name .= '.pm';
        eval { require $require_name; };

        my $PACKAGE_DIR = $conf->{packagedir};

        if ($@) { $logger->info("Error while compilling $poco_start: $@"); return; }
        eval {
            $poco_start->create(
                path     => $path,
                packages => $PACKAGE_DIR,
                gsID     => $gsID,
                port     => $port,
                params   => @params
            );
        };

        if ($@) {
            $logger->info("Error while starting $poco_start: $@");
            return;
        }

        $gslogger->warn( "Nightlyrestart finished !", $gsID );
        $gslogger->setstatus("started");
        $sth1->finish();
        $sth2->finish();
    }

    $sth->finish;

    $dbh->disconnect();

    POE::Kernel->alarm( nightlyrestart => ( int( time() ) + ( 24 * 60 * 60 ) ) );
}

sub add_gameserver {
    DEBUG;
    my $port = $_[ARG0];
    my $pid  = $_[ARG1];
    $_[HEAP]->{gameserver}->{$port} = $pid;
}

sub delete_gameserver {
    DEBUG;
    my $port = $_[ARG0];
    delete $_[HEAP]->{gameserver}->{$port};
}

sub start {
    DEBUG;
    my $user_id = $>;
    $logger->info("version $VERSION Starting as user $user_id");

    $_[HEAP]->{fifo} = POE::Wheel::FollowTail->new(
        Filename   => $PIPE_DIRECTORY,
        InputEvent => "pipe_data",
        ResetEvent => "pipe_reset",
        ErrorEvent => "pipe_error",
    ) or $logger->warn("Couldn't spawn wheel: $!");

    #POE::Kernel->yield('nightlyrestart');

    $_[KERNEL]->alarm( nightlyrestart => ( ( int( time() / 86400 ) * 86400 ) + ( 24 * 60 * 60 ) + ( 3 * 60 * 60 ) ) );

    POE::Kernel->sig( INT => "sig_shutdown" );
    POE::Kernel->alias_set('catepod');
}

sub stop {
    DEBUG;
    POE::Kernel->alias_remove('catepod');

    $logger->info("Stopping.");

    flock( $lockfile, LOCK_UN ) or $logger->warn("Failed to unlock $PIDFILE: $!");
}

sub pipe_data {
    DEBUG;
    my $input = $_[ARG0];
    my $hashref;
    eval { $hashref = from_json($input); };
    if ($@) {
        $logger->warn("received invalid JSON: $input");
        return;
    }
    POE::Kernel->yield( 'process_command', $hashref );
}

sub pipe_reset {    # we don't do anything here, pipes can't be reset.
    DEBUG;
}

sub pipe_error {
    DEBUG;
    my ( $operation, $errnum, $errstr, $id ) = @_[ ARG0 .. ARG3 ];
    $logger->info("pipe error while $operation: $errnum, $errstr, $id");
}

sub sig_shutdown {
    DEBUG;
    $logger->warn("received shutdown signal, exiting.");
    delete $_[HEAP]->{fifo};    # freeing the resource we are watching
    foreach my $key ( keys %{ $_[HEAP]->{gameserver} } ) {
        POE::Kernel->post( $key => "shutdown" );
    }
    $_[KERNEL]->sig_handled();
}

sub process_command {
    DEBUG;
    my $data = $_[ARG0];
    if ( !$data->{command} ) {
        $logger->warn("invalid json sent: command is missing");
        return;
    }
    if ( $data->{command} eq 'quit' ) {
        $logger->warn("received quit command, exiting...");
        delete $_[HEAP]->{fifo};
        POE::Kernel->yield('sig_shutdown');
    }
    elsif ( $data->{command} eq 'start' ) {
        my $port       = $data->{port};
        my $game       = $data->{game};
        my $params_ref = $data->{params};
        my $install    = $data->{install};
        my $gsID       = $data->{gsID};
        my $poco;
        my $gsdir = $data->{path};

        unless ( $port >= 1024 && $port <= 65535 ) {
            $logger->warn("server port: '$port' is to low, or to high.");
            return;
        }

        unless ( $poco = $conf->{games}->{$game} ) {
            $logger->warn(
                "Do not know what to do with game '$game', perhaps you forgot to specify a poco for it in the config?"
            );
            return;
        }

        unless ( @$params_ref > 0 ) {
            $logger->warn("cannot start gameserver '$port'  without params.");
            return;
        }

        unless ($gsID) {
            $logger->warn("You don't gave me the server ID, exiting...");
            return;
        }

        my $ins;
        if    ( $install eq "install" )   { $ins = ", while install it"; }
        elsif ( $install eq "reinstall" ) { $ins = ", while reinstalling it"; }

        $logger->info( "Starting $poco with params: '" . "@$params_ref" . "' in: '$gsdir'" . $ins . "." );

        # starting the gameserver
        my $require_name = $poco;
        $require_name =~ s/::/\//g;
        $require_name .= '.pm';
        eval { require $require_name; };

        my $PACKAGE_DIR = $conf->{packagedir};

        $logger->info($params_ref);

        if ($@) { $logger->info("Error while compilling $poco: $@"); return; }
        eval {
            $poco->create(
                path     => $gsdir,
                params   => $params_ref,
                install  => $install,
                packages => $PACKAGE_DIR,
                port     => $port,
                gsID     => $gsID
            );
        };

        if ($@) {
            $logger->info("Error while starting $poco: $@");
            return;
        }
    }
    elsif ( $data->{command} eq "stop" ) {
        my $path = $data->{path};
        my $gsID = $data->{gsID};

        if ( $data->{install} eq "remove" ) {
            if ( !$_[KERNEL]->post( $path => 'remove' ) ) {
                if ( $! eq "No such process" ) {
                    $gslogger->warn( "The server doesn't run, aborting deinstallation.", $gsID );
                    $logger->info("The server have to been running before we can remove it.");
                }
                else {
                    $logger->warn("Error while post remove in $path: $!");
                    return;
                }
            }
        }

        $logger->info( "Attempting to stop Gameserver in: " . $path );

        if ( !$_[KERNEL]->post( $path => '_stop_gameserver', "gsID" => $gsID ) ) {
            if ( $! eq "No such process" ) {
                $logger->warn("There doesn't run a gameserver in $path");
                $gslogger->warn( "The gameserver doesn't run, can't stop it.", $gsID );
                $gslogger->setstatus( "stopped", $gsID );
            }
            else {
                $logger->warn("Error while posting '_stop_gameserver' to $path: $!");
                return;
            }
        }

    }
    elsif ( $data->{command} eq "restart" ) {
        my $path = $data->{path};
        my $port = $data->{port};
        $logger->info( "Attempting to restart Gameserver in: " . $path );

        if ( !$_[KERNEL]->post( $path => 'stop' ) ) {
            $logger->warn("Couldn't stop Server in $path, maybe there does not run a server ?: $!");
            return;
        }

        if ( !$_[KERNEL]->post( $path => '_start_gameserver' ) ) {
            $logger->warn("Couldn't start Server in $path: $!");
            return;
        }
    }
    elsif ( $data->{command} eq "install_mod" ) {
        my $path        = $data->{path};
        my $mod         = $data->{mod};
        my $install     = $data->{install};
        my $PACKAGE_DIR = $conf->{packagedir} . "/Addons/";
        my $gsID        = $data->{gsID};
        my $poco;

        if ( !-e $PACKAGE_DIR ) {
            $logger->warn("Addons directory '$PACKAGE_DIR' does not exists");
            $gslogger->warn( "Coudln't find direcotry with Addon source files.", $gsID );
            $gslogger->setstatus( "modinstallfail", $gsID );
            return;
        }

        if ( !-e $path ) {
            $logger->warn("There isnt installed a gameserver in $path !");
            $gslogger->warn( "There isn't installed a gameserver in $path, please reinstall it.", $gsID );
            $gslogger->setstatus( "modinstallfail", $gsID );
            return;
        }

        unless ( $poco = $conf->{mods}->{$mod} ) {
            $logger->warn("Do not know what todo with $mod, perhabs you forgot to specify a poco for $mod ?");
            $gslogger->warn(
                "Don't know what I should do with $mod, perhabs it has been forgotten to specify a poco for it.",
                $gsID );
            $gslogger->setstatus( "modinstallfail", $gsID );
            return;
        }

        my $require_name = $poco;
        $require_name =~ s/::/\//g;
        $require_name .= '.pm';
        eval { require $require_name; };
        if ($@) { $logger->info("Error while compilling $poco: $@"); return; }
        eval {
            $poco->create(
                path        => $path,
                install     => $install,
                mod         => $mod,
                package_dir => $PACKAGE_DIR,
                gsID        => $gsID
            );
        };

        if ($@) {
            $logger->info("Error while starting $poco: $@");
            return;
        }

    }
    elsif ( $data->{command} eq "user_add" ) {
        my $username = $data->{username};
        my $password = $data->{password};

        my $home_dir = $GSWI_DIR . "/gameserver/" . $username . "/";

        open my $filehandle, '<', '/etc/passwd';
        my @slurp = <$filehandle>;
        close $filehandle;

        if ( grep { $_ =~ m/.*$username.*$/ } @slurp ) {
            $logger->warn("Couldn't add $username to system: User already exists.");
            return;
        }

        if ( !Linux::usermod->add( $username, $password, 500, 1000, "catepod - GSWI USER", $home_dir, "/bin/false" ) ) {
            $logger->warn("Failed to add $username to system: $!");
            return;
        }

        if ( !mkdir($home_dir) ) {
            $logger->warn("Failed to create user's home directory.");
            return;
        }

        my $user   = Linux::usermod->new($username);
        my $userID = $user->get(2);
        my $gID    = $user->get(3);

        $logger->warn($userID);

        if ( !chown $userID, $gID, $home_dir ) {
            $logger->warn("Couldn't give $username rights to $home_dir: $!");
            return;
        }

        $logger->info("User $username added to system");

    }
    elsif ( $data->{command} eq "user_del" ) {
        my $username = $data->{username};
        my $home_dir = $GSWI_DIR . "/gameserver/" . $username . "/";

        open my $filehandle, '<', '/etc/passwd';
        my @slurp = <$filehandle>;
        close $filehandle;

        if ( !grep { $_ =~ m/.*$username.*$/ } @slurp ) {
            $logger->warn("Couldn't delete $username: No such user");
            return;
        }

        if ( !rmtree($home_dir) ) {
            $logger->warn("Couldn't delete user's home dir: $!");
            $logger->warn("$username not deleted !");
            return;
        }

        my $user = Linux::usermod->new($username);
        if ( !Linux::usermod->del($username) ) {
            $logger->warn("Coudln't delete $username from system: $!");
            $logger->warn("$username not deleted !");
            return;
        }

        $logger->info("$username successfully removed !");

    }
    elsif ( $data->{command} eq "install_map" ) {
        my $mapname   = $data->{mapname};
        my $port      = $data->{port};
        my $path      = "$GSWI_DIR/gameserver/$port";
        my $FD_SERVER = $data->{fastdownloadserver};
        my $FD_LINK   = $data->{fastdownloadlink};
        my $DL_LINK   = "$FD_SERVER/$FD_LINK";

        if ( !-e "$path" ) {
            $logger->warn("It seems, that in $path isn't installed a gameserver, aborting.");
            return;
        }

        if ( $mapname !~ m/.*bsp/ ) {
            if ( !chdir($path) ) {
                $logger->warn("Couldn't chdir to $path: $!");
                return;
            }

            system(" wget $DL_LINK ");

            $logger->warn("Installed $mapname successful to server in $path.");
        }
        else {
            $logger->warn("$mapname isn't a regular mapfile name or format, aborting.");
            return;
        }

    }
    elsif ( $data->{command} eq "process_command" ) {
        my $cmd  = $data->{cmd};
        my $path = $data->{path};

        if ( !$_[KERNEL]->post( $path => '_process_command', "command" => $cmd ) ) {
            $logger->warn("Error while processing command $cmd to $path: $!");
            return;
        }
    }
    else {
        $logger->warn( "invalid json sent: couldn't understand command '" . $data->{command} . "'" );
    }
}

